disablePathToLower = true
baseURL = "https://www.brysgo.com/"
languageCode = "en-us"
title = "BRYSGO"
theme = ["custom", "minimal"]
disqusShortname = "brysgo" # delete this to disable disqus comments


[params]
    author = "Bryan Goldstein"
    description = "Personal blog of Bryan Goldstein. Exploring Web Development, DevOps, AI, and more."
    githubUsername = "brysgo"
    accent = "red"
    showBorder = true
    backgroundColor = "white"
    font = "Raleway" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "solarized-dark"
    highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift"]
    copyright = "© 2026 Bryan Goldstein, All rights reserved."

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true


# Social icons to be shown on the right-hand side of the navigation bar
# The "name" field should match the name of the icon to be used
# The list of available icons can be found at http://fontawesome.io/icons/

[[menu.icon]]
    url = "mailto:brysgo@gmail.com"
    name = "envelope-o"
    weight = 1

[[menu.icon]]
    url = "https://github.com/brysgo/"
    name = "github"
    weight = 2

[[menu.icon]]
    url = "https://twitter.com/brysgo/"
    name = "twitter"
    weight = 3

[[menu.icon]]
    url = "https://www.linkedin.com/in/brysgo/"
    name = "linkedin"
    weight = 4

[[menu.icon]]
    url = "https://stackoverflow.com/users/386294/brysgo"
    name = "stack-overflow"
    weight = 5

[services.googleAnalytics]
  ID = "G-8RCNSGCV00"
