name: Main workflow

on:
  push:
    branches:
      - hugo

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "latest"
      - name: clean up scss
        run: sudo rm -rf ./public/css/*.scss

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: contains(github.ref, 'hugo')
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: master
          PUBLISH_DIR: ./public
