on:
  schedule:
    - cron: "* 8,13,17 * * *"
name: Download posts from google sheets
jobs:
  download-posts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: hugo
      - uses: actions/setup-node@v2-beta
        with:
          node-version: "14"
      - name: setup yarn version
        run: cd scripts/ && yarn set version berry --only-if-needed && cd ../
      - name: run blog post generator
        run: cd scripts/ && yarn node ./posts-from-gsheets.js && cd ../
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Download new blog posts from spreadsheet
      - name: trigger deploy
        run: curl -H "Accept: application/vnd.github.everest-preview+json" \ -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \ --request POST \ --data '{"event_type": "manual-deploy"}' \ https://api.github.com/repos/brysgo/brysgo.github.io/dispatches
